### PR TITLE
Fixes #16, Added environment variables

### LINKED ISSUE #16: Missing Environment Variables in .env.template
**Issue Description:**  
The `.env.template` file is designed to assist users in configuring all the required environment variables. However, it currently lacks some of these variables. The objective in addressing this issue is to include all the necessary variables in the template to facilitate user configuration.

### PR DESCRIPTION
**Pull request by JolanThomassin**
Fixes #16
 - Added environment variable: DB_SERVER_CONTAINER_NAME and PGDATA

### CODE REVIEW

**Review by rngadam — CHANGES_REQUESTED** [review]
I would expect the documentation to setup the project to also explain those new environment variables (and the existing ones if such doc doesn't already exist)

**Comment by JolanThomassin** [comment]
The most recent commit ([ba152c5](https://github.com/ai-cfia/louis-db/pull/18/commits/ba152c5aa8400365152ef62fe1a3cc748f4117c6)) involved **incorporating documentation** regarding both the new and pre-existing **environment variables**. Initially, I opted to provide a **brief description for each variable** within the `DEVELOPER.md` file. However, it might be more practical to create a dedicated document named `ENVIRONMENT-VARIABLES.md`. This would facilitate **more comprehensive descriptions**, especially if we anticipate the introduction of numerous new variables in the future. Additionally, we can consider including this information within the configuration section of the `READ.me` file in the `\bin` directory for better accessibility.

I'm awaiting a decision on which option would be **the most suitable for the project**.

**Comment by JolanThomassin** [comment]
I'll require **confirmation on the variable descriptions** as well, as I'm uncertain about their precise usage within the project.

**Review by rngadam — APPROVED** [review]
Looks fine for a first pass, you can add to the doc as you understand more of the system. 

...for environment variables, I've discussed with @k-allagbe the idea of having a declarative file env.yml describing each environment variable and its requirements (regexp, filepath, url, etc). I'm pretty sure such a library should already exists.

**Pull request merged**
